---
- name: add host to /etc/hosts for in-addr-arpa-reverse-dns
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ item }}"
    state: present
  with_items:
    - "{{ reverse_dns_hosts }}"

- name: set hostname
  hostname:
    name: "{{ host_name }}"

- name: add local hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ inn_ips.split(',')[0] }} {{ host_name }}"

# vim: sw=2 ft=ansible
